"""add column enrolment

Revision ID: d417c788e0a3
Revises: 1d4866516fa8
Create Date: 2025-04-20 20:05:58.014676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d417c788e0a3"
down_revision: Union[str, None] = "1d4866516fa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("people", sa.Column("enrolment", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "people", ["enrolment"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "people", type_="unique")
    op.drop_column("people", "enrolment")
    # ### end Alembic commands ###
